DROP TABLE IF EXISTS point_of_interest;

CREATE TABLE point_of_interest (
    poi_id UUID PRIMARY KEY,
    created_by_user_id UUID,
    organization_id UUID,
    poi_name VARCHAR(255),
    poi_type VARCHAR(255),
    poi_category VARCHAR(255),
    poi_description CLOB,
    latitude DOUBLE,
    longitude DOUBLE,
    address_street_number VARCHAR(255),
    address_street_name VARCHAR(255),
    address_city VARCHAR(255),
    address_postal_code VARCHAR(255),
    address_country VARCHAR(255),
    address_state_province VARCHAR(255),
    address_informal VARCHAR(255),
    website_url VARCHAR(255),
    operation_time_plan CLOB,
    poi_contacts CLOB,
    poi_images_urls VARCHAR(255) ARRAY,
    poi_amenities VARCHAR(255) ARRAY,
    poi_keywords VARCHAR(255) ARRAY,
    popularity_score FLOAT,
    is_active BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
